nodeLinker: pnp

packageExtensions:
  "@semantic-release/commit-analyzer@*":
    dependencies:
      conventional-changelog-angular: "*"
  "@semantic-release/release-notes-generator@*":
    dependencies:
      conventional-changelog-angular: "*"
  "@mrbernnz/semantic-release-calver@*":
    dependencies:
      date-fns: "^2.30.0"
  "semantic-release@*":
    dependencies:
      conventional-changelog-angular: "*"
