name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Enable yarn berry
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .tool-versions

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: release_contents
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags manually
        run: git fetch --force --tags

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: release_contents
          path: dist

      - name: Enable yarn berry
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .tool-versions

      - name: Install dependencies
        run: |
          # Force node_modules just for this run to avoid PnP issues
          yarn config set nodeLinker node-modules
          yarn install --immutable
        env:
          # This ensures the date-fns version you need is respected
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Release (or dry-run on PR)
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            yarn semantic-release --dry-run
          else
            yarn semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
